[package]
name = "inexor-rgf-core-di"
description = "Inexor - Reactive Graph Flow - Dependency Injection"
version = "2.0.0"
authors = [
    "dmitryb.dev@gmail.com",
    "Andreas Schaeffer <hanack@nooblounge.net>"
]
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = [
    "dependency-injection",
    "inversion-of-control",
    "di",
    "ioc"
]
repository = "https://github.com/aschaeffer/inexor-rgf-core-di"

[workspace]
members = [ "crates/*" ]

[dependencies]
inexor-rgf-core-di-codegen = { path = "crates/inexor-rgf-core-di-codegen", version = "2.0.0" }
config = "0.11"
serde = { version = "1.0", features = [ "derive" ] }
regex = "1.5"
lazy_static = "1.4.0"
log = "0.4"

[features]
async = [ "inexor-rgf-core-di-codegen/async" ]
