[package]
name = "waiter_di"
description = "Inexor - Reactive Graph Flow - Dependency injection"
version = "1.6.5"
authors = [
    "dmitryb.dev@gmail.com",
    "Andreas Schaeffer <hanack@nooblounge.net>"
]
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = [ "dependency-injection", "inversion-of-control", "di", "ioc"]
repository = "https://github.com/dmitryb-dev/waiter"

[workspace]
members = [ "crates/*" ]

[dependencies]
waiter_codegen = { path = "crates/waiter_codegen", version = "1.6.5" }
config = "0.11"
serde = { version = "1.0", features = [ "derive" ] }
regex = "1.5"
lazy_static = "1.4.0"
log = "0.4"

[features]
async = [ "waiter_codegen/async" ]
